---
go_root: /usr/local/go
go_path: "{{ ansible_env.HOME }}/.go"
go_tools:
  - golang.org/x/lint/golint@latest
  - github.com/go-delve/delve/cmd/dlv@latest
  - golang.org/x/tools/gopls@latest
  - golang.org/x/tools/cmd/goimports@latest
  - github.com/ramya-rao-a/go-outline@latest
  - github.com/fatih/gomodifytags@latest
  - github.com/josharian/impl@latest
  - github.com/cweill/gotests/gotests@latest
cleanup_archive: true
